### ISSUE TITLE
Setup Styled Components

### ISSUE THREAD

**Issue by thecodeclimber** [thecodeclimber/bluejay-redparts#1]
# Description
Install Styled Components and related libraries on site on Site

# Resources

* Styled Components: https://styled-components.com/docs/basics#installation

* Styled Map: https://github.com/scf4/styled-map

* NextJS Integration:  https://github.com/vercel/next.js/tree/canary/examples/with-styled-components

# Acceptance Criteria

* Styled Components is installed properly for next.js

* Stlyled Map is installed

**Comment by thecodeclimber** [comment]
@lokesh75way

Please note that I added a new resource above.  It is a link to the a repository that shows how to integrate styled-components with next.js.

**Comment by lokesh75way** [comment]
@thecodeclimber 
**Here is the commit link**: https://github.com/thecodeclimber/bluejay-redparts/commit/c1ee2ee240baaeb7c4d4c21f23d00ac720427c7a

I created new branch `issue/#1--setup-styled-components` from `main` branch
Please tell me do I create PR for `main` or not?
Thanks.

**Comment by thecodeclimber** [comment]
@lokesh75way 

A couple of question about the `.babelrc` file.

```
{
    "presets": ["next/babel"],
    "plugins": [
        "inline-react-svg",
        [
            "babel-plugin-styled-components",
            { "ssr": true, "displayName": true, "preprocess": false }
        ]
    ]
}
```

* Why do we need `displayName: true` -- isn't that the default setting?
* What is `preprocess: false` -- I could not find anything about that in the documentation:  https://styled-components.com/docs/tooling#babel-plugin

**Comment by thecodeclimber** [comment]
@lokesh75way 

We need to add support for TypeScript:

* https://styled-components.com/docs/api#typescript
* https://styled-components.com/docs/tooling#typescript-plugin

**Comment by thecodeclimber** [comment]
@lokesh75way 

Please create a `develop` based on the `main` branch and we will merge all changes into there.  When we finish the milestone and test that it works properly, we can then merge develop back into main.

**Comment by thecodeclimber** [comment]
@lokesh75way 

Note -- when an issue is in `review`, please feel free to start a new issue.

**Comment by lokesh75way** [comment]
> @lokesh75way
> 
> A couple of question about the `.babelrc` file.
> 
> ```
> {
>     "presets": ["next/babel"],
>     "plugins": [
>         "inline-react-svg",
>         [
>             "babel-plugin-styled-components",
>             { "ssr": true, "displayName": true, "preprocess": false }
>         ]
>     ]
> }
> ```
> 
> * Why do we need `displayName: true` -- isn't that the default setting?
> * What is `preprocess: false` -- I could not find anything about that in the documentation:  https://styled-components.com/docs/tooling#babel-plugin

**Comment by lokesh75way** [comment]
@thecodeclimber 
> A couple of question about the `.babelrc` file.
> 
> ```
> {
>     "presets": ["next/babel"],
>     "plugins": [
>         "inline-react-svg",
>         [
>             "babel-plugin-styled-components",
>             { "ssr": true, "displayName": true, "preprocess": false }
>         ]
>     ]
> }
> ```
> 
> * Why do we need `displayName: true` -- isn't that the default setting?
> * What is `preprocess: false` -- I could not find anything about that in the documentation:  https://styled-components.com/docs/tooling#babel-plugin

- Yes it's default true, I will remove it.
- Updated preprocess value false because it automatically disables the minification of css
Read from [this](https://www.npmjs.com/package/babel-plugin-styled-components/v/1.1.7) documentation: https://www.npmjs.com/package/babel-plugin-styled-components/v/1.1.7

**Comment by lokesh75way** [comment]
- Added typescript-plugin-styled-components library
- Created PR for develop
- PR link: https://github.com/thecodeclimber/bluejay-redparts/pull/15
- Github commit link to verify code: https://github.com/thecodeclimber/bluejay-redparts/commit/52a29cfa48f8ba34d60dc3e57b19b634950ba0ae

**Comment by thecodeclimber** [comment]
@lokesh75way 

In terms of typescript shouldn't we also add this:  https://babeljs.io/docs/en/babel-preset-typescript -- based on this:

> NOTE
Now that Babel 7 is out and the [TypeScript preset](https://babeljs.io/docs/en/babel-preset-typescript) is available, it's now possible to use the [styled-components babel plugin](https://styled-components.com/docs/tooling#babel-plugin) in conjunction with TypeScript.

**Comment by lokesh75way** [comment]
- Added @babel/preset-typescript and @babel/plugin-transform-typescript libraries
- Github commit link to verify code: https://github.com/thecodeclimber/bluejay-redparts/commit/dd05684ccd226c45fab4aaabc93757cba11ea81c
- PR link: https://github.com/thecodeclimber/bluejay-redparts/pull/15

**Comment by thecodeclimber** [comment]
@lokesh75way -- Done.  Thanks :).
