### ISSUE TITLE
Create & Use "MobileSearch" Styled Components

### ISSUE THREAD

**Issue by thecodeclimber** [thecodeclimber/bluejay-redparts#10]
# Description

Create MobileSearch Styled Components from _mobile-search.scss

**NOTE:** Follow same format & procedure for #6 

**NOTE:**  Check out the mobile header search styles in the `mobile-header-variant-two.scss` file.

# Resources

* https://github.com/thecodeclimber/bluejay-redparts/blob/main/src/scss/mobile/_mobile-searcg.scss
* https://github.com/thecodeclimber/bluejay-redparts/blob/main/src/components/mobile/MobileHeader.tsx
* https://github.com/thecodeclimber/bluejay-redparts/blob/main/src/scss/style.mobile-header-variant-two.scss

# Acceptance Criteria

- [ ] Create Styled Components
- [ ] Use Styled Components

**Comment by lokesh75way** [comment]
Github commit link to verify code: https://github.com/thecodeclimber/bluejay-redparts/commit/6c088d0d6c77a89d0945e3e9fc37f1df83701bdc

PR link: https://github.com/thecodeclimber/bluejay-redparts/pull/26

@thecodeclimber

**Comment by lokesh75way** [comment]
@thecodeclimber hii,
I have a question if a element have more that 1 classes I have to make only one styled component or more that one and if more that one then how ? please suggest thank you ...

**Comment by thecodeclimber** [comment]
@lokesh75way 

Sorry I didn't respond earlier.  Can you point me to the file and line number of the specific example?

**Comment by thecodeclimber** [comment]
@lokesh75way 

With styled components, you can make references to other Styled Components:  https://styled-components.com/docs/advanced#referring-to-other-components

You can also pass props:  https://styled-components.com/docs/basics#passed-props

So, if an element as 2 or more classes, you can combine those classes as styled components as follows:

```
const ClassTwo = styled.div`
  // styles go here
`

const ClassOne = styled.div`
  ${props => props.classTwo && ClassTwo} // I don't know if this is the right syntax
`

<ClassOne classTwo>...</ClassOne>
```

In short, the idea is that we have both a StyledComponent for `ClassTwo` and a prop.  When we use that prop with `ClassOne` we then pull in those styles into `ClassOne`.  

There is an exception to the rule, though -- and that is when the theme uses bootstrap utility classes -- like `d-flex-none`.  In that case, just use the utility class along with the Styled Component.

Please let me know if that answers your question.

**Comment by thecodeclimber** [comment]
@lokesh75way 

please also update me on this issue and let me know where we stand with it.  thanks.
