### ISSUE TITLE
Create Milestones & Issues for Header Styled Components

### ISSUE THREAD

**Issue by thecodeclimber** [thecodeclimber/bluejay-redparts#11]
# Description

Create milestones & issues for the different aspects of the Header Styled Components.

**NOTE: **  Follow format of the Mobile Header milestones and issues that I created.

# Resource

* https://github.com/thecodeclimber/bluejay-redparts/blob/main/src/scss/style.header-classic-variant-four.scss
* https://github.com/thecodeclimber/bluejay-redparts/blob/main/src/scss/_style.header.scss

# Acceptance Criteria

- [ ] Created Milestones
- [ ] Created Issues

**Comment by lokesh75way** [comment]
hi @thecodeclimber
I have a question, can you please tell me do we have to create the styled component for all the files in the Header folder like: 
Dropdown.tsx, Logo.tsx, Menu.tsx, search.tsx etc. Or only for Header.tsx in this ticket ?
