### ISSUE TITLE
Figure Out & Create Milestones & Issues For MobileMenu Component

### ISSUE THREAD

**Issue by thecodeclimber** [thecodeclimber/bluejay-redparts#13]
# Description

Figure out what style components need to be created based off the `MobileMenu` component in `Layouts.tsx`

# Explanation

https://www.loom.com/share/3350c9663e8241a0bb028a8ab19d8984

# Resource

* https://github.com/thecodeclimber/bluejay-redparts/blob/main/src/components/Layout.tsx

# Acceptance Criteria

- [ ] Created Milestones
- [ ] Created Issues

**Comment by lokesh75way** [comment]
Github commit link to verify code: https://github.com/thecodeclimber/bluejay-redparts/pull/28/commits/ccefdffc51563f168ec35cd6c22e704de67110a0

PR link: https://github.com/thecodeclimber/bluejay-redparts/pull/28

@thecodeclimber
