### ISSUE TITLE
Create Initial Theme

### ISSUE THREAD

**Issue by thecodeclimber** [thecodeclimber/bluejay-redparts#3]
# Description

Convert Redparts Sass Theme into Styled Components Theme

# Acceptance Criteria

* Theme successfully converted

**Comment by lokesh75way** [comment]
Hi! @thecodeclimber 
I have a query about this ticket. Please can you confirm that, do I need to convert all (for example : `_variables.scss, _block-finder.scss, _block-products-carousel.scss` etc...) the `Sass Theme into Styled Components` or only for the common components, like button, title, etc...?

**Comment by thecodeclimber** [comment]
@lokesh75way 

What I had in mind were the variables files.  But as I look at it now, I think we should skip this step and we'll come back to it when need be.
