### ISSUE TITLE
Create & Use "Mobile Header" Styled Components

### ISSUE THREAD

**Issue by thecodeclimber** [thecodeclimber/bluejay-redparts#6]
# Description

Convert mobile scss files to styled components

# Explanation

## Create Styled Components

```
.mobile-header --> const MobileHeader = styled.div
.mobile-header__body --> const MobileHeaderBody = styled.div
.mobile-header__menu-button --> const MobileHeaderMenuButton = styled.button
...
```

**NOTE**:  Check `MobileHeader.tsx` for which html tags to use (see resources below)

**NOTE:** You will need to create a `MobileContainer` Styled Component (see both resource files below for when and how to use it).

## Use Styled Components

Use the new Styled Components in the `MobileHeader.tsx` file.

When using, alias the components as follows: `import { MobileHeaderBody as Body, MobileHeaderMenuButton as MenuButton}...`

# Resources

* https://github.com/thecodeclimber/bluejay-redparts/blob/main/src/scss/mobile/_mobile-header.scss
* https://github.com/thecodeclimber/bluejay-redparts/blob/main/src/components/mobile/MobileHeader.tsx

# Acceptance Criteria

- [x] Create Styled Components
- [x] Use Styled Components

**Comment by lokesh75way** [comment]
* Github commit link to verify code: https://github.com/thecodeclimber/bluejay-redparts/commit/839393d6d1846c84e35ae00326449a880451a219
* PR link: https://github.com/thecodeclimber/bluejay-redparts/pull/19
