### ISSUE TITLE
Create & Use "MobileLogo" Styled Components 

### ISSUE THREAD

**Issue by thecodeclimber** [thecodeclimber/bluejay-redparts#8]
# Description

Create MobileLogo Styled Components from _mobile-logo.scss

**NOTE:** Follow same format & procedure for #6 

# Resources

* https://github.com/thecodeclimber/bluejay-redparts/blob/main/src/scss/mobile/_mobile-logo.scss
* https://github.com/thecodeclimber/bluejay-redparts/blob/main/src/components/mobile/MobileHeader.tsx

# Acceptance Criteria

- [x] Create Styled Components
- [x] Use Styled Components

**Comment by lokesh75way** [comment]
* Github commit link to verify code: https://github.com/thecodeclimber/bluejay-redparts/commit/cbe690ce5bbafe4b7683bc6872efd7411c9b60a9
* PR link: https://github.com/thecodeclimber/bluejay-redparts/pull/20
